import type { Config } from 'tailwindcss';

const config: Config = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        secondary: 'var(--secondary)',
        'secondary-foreground': 'var(--secondary-foreground)',
        destructive: 'var(--destructive)',
        muted: 'var(--muted)',
        'muted-foreground': 'var(--muted-foreground)',
        accent: 'var(--accent)',
        'accent-foreground': 'var(--accent-foreground)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        card: 'var(--card)',
        'card-foreground': 'var(--card-foreground)',
        popover: 'var(--popover)',
        'popover-foreground': 'var(--popover-foreground)',
        input: 'var(--input)',
        border: 'var(--border)',
        ring: 'var(--ring)',
        sidebar: 'var(--sidebar)',
        'sidebar-foreground': 'var(--sidebar-foreground)',
        'sidebar-primary': 'var(--sidebar-primary)',
        'sidebar-primary-foreground': 'var(--sidebar-primary-foreground)',
        'sidebar-accent': 'var(--sidebar-accent)',
        'sidebar-accent-foreground': 'var(--sidebar-accent-foreground)',
        'sidebar-border': 'var(--sidebar-border)',
        'sidebar-ring': 'var(--sidebar-ring)',
        // BH Colors
        'bh-bg': 'var(--bh-bg)',
        'bh-black': 'var(--bh-black)',
        'bh-blue': 'var(--bh-blue)',
        'bh-blue-tint': 'var(--bh-blue-tint)',
        'bh-gray-600': 'var(--bh-gray-600)',
        'bh-gray-700': 'var(--bh-gray-700)',
        'bh-red': 'var(--bh-red)',
        'bh-red-tint': 'var(--bh-red-tint)',
        'bh-success': 'var(--bh-success)',
        'bh-white': 'var(--bh-white)',
        'bh-yellow': 'var(--bh-yellow)',
        // IH Colors
        'ih-accent': 'var(--ih-accent)',
        'ih-bg': 'var(--ih-bg)',
        'ih-border': 'var(--ih-border)',
        'ih-border-strong': 'var(--ih-border-strong)',
        'ih-negative': 'var(--ih-negative)',
        'ih-positive': 'var(--ih-positive)',
        'ih-surface': 'var(--ih-surface)',
        'ih-surface-warm': 'var(--ih-surface-warm)',
        'ih-text': 'var(--ih-text)',
        'ih-text-muted': 'var(--ih-text-muted)',
        'ih-text-secondary': 'var(--ih-text-secondary)',
        // Semantic Colors
        'color-error': 'var(--color-error)',
        'color-error-foreground': 'var(--color-error-foreground)',
        'color-info': 'var(--color-info)',
        'color-info-foreground': 'var(--color-info-foreground)',
        'color-success': 'var(--color-success)',
        'color-success-foreground': 'var(--color-success-foreground)',
        'color-warning': 'var(--color-warning)',
        'color-warning-foreground': 'var(--color-warning-foreground)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        m: 'var(--radius-m)',
        pill: 'var(--radius-pill)',
      },
      fontFamily: {
        display: 'var(--font-display, "Space Grotesk", sans-serif)',
        mono: 'var(--font-mono, "Space Mono", monospace)',
        primary: 'var(--font-primary, "JetBrains Mono", monospace)',
        secondary: 'var(--font-secondary, "Geist", sans-serif)',
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};

export default config;
